In [1]:
import pandas as pd

df =pd.read_csv('swiggy_customer_data.csv')
df.head()

,customer_id,age,city,orders_last_30_days,avg_order_value,days_since_last_order,coupon_used_last_month,customer_support_calls,churn
0,10001,56,Bangalore,19,1472,36,1,9,0
1,10002,46,Mumbai,3,1081,46,0,5,1
2,10003,32,Bangalore,9,1020,75,1,6,0
3,10004,25,Chennai,2,821,36,1,2,0
4,10005,38,Bangalore,8,1284,48,0,6,0

### Data quality

In [2]:
print("Shape:", df.shape)

print("\nColumns:")
print(df.columns)

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicates:")
print(df.duplicated().sum())

Shape: (500, 9)

Columns:
Index(['customer_id', 'age', 'city', 'orders_last_30_days', 'avg_order_value',
       'days_since_last_order', 'coupon_used_last_month',
       'customer_support_calls', 'churn'],
      dtype='object')

Data Types:
customer_id                int64
age                        int64
city                      object
orders_last_30_days        int64
avg_order_value            int64
days_since_last_order      int64
coupon_used_last_month     int64
customer_support_calls     int64
churn                      int64
dtype: object

Missing Values:
customer_id               0
age                       0
city                      0
orders_last_30_days       0
avg_order_value           0
days_since_last_order     0
coupon_used_last_month    0
customer_support_calls    0
churn                     0
dtype: int64

Duplicates:
0

In [3]:
df.describe(include='all')

,customer_id,age,city,orders_last_30_days,avg_order_value,days_since_last_order,coupon_used_last_month,customer_support_calls,churn
count,500.000000,500.000000,500,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
unique,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,Bangalore,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,147,NaN,NaN,NaN,NaN,NaN,NaN
mean,10250.500000,39.326000,NaN,9.178000,816.694000,43.390000,0.518000,4.524000,0.140000
std,144.481833,12.200386,NaN,5.816354,413.355845,26.335242,0.500176,2.844223,0.347335
min,10001.000000,18.000000,NaN,0.000000,101.000000,0.000000,0.000000,0.000000,0.000000
25%,10125.750000,29.000000,NaN,4.000000,455.000000,20.000000,0.000000,2.000000,0.000000
50%,10250.500000,41.000000,NaN,9.000000,842.500000,42.000000,1.000000,5.000000,0.000000
75%,10375.250000,50.000000,NaN,14.000000,1163.000000,67.000000,1.000000,7.000000,0.000000
max,10500.000000,59.000000,NaN,19.000000,1494.000000,89.000000,1.000000,9.000000,1.000000